/// Hive Database Service
///
/// Initializes and manages local Hive database for offline-first architecture.

import 'package:hive_flutter/hive_flutter.dart';
import '../models/local_application.dart';
import '../models/local_address.dart';
import '../models/local_family_member.dart';
import '../models/local_document.dart';

class HiveService {
  static const String applicationsBoxName = 'applications';
  static const String addressesBoxName = 'addresses';
  static const String familyMembersBoxName = 'family_members';
  static const String documentsBoxName = 'documents';
  static const String settingsBoxName = 'settings';
  static const String userDataBoxName = 'user_data';

  /// Initialize Hive database
  static Future<void> init() async {
    // Initialize Hive with Flutter
    await Hive.initFlutter();

    // Register type adapters (generated by build_runner)
    Hive.registerAdapter(LocalApplicationAdapter());
    Hive.registerAdapter(LocalAddressAdapter());
    Hive.registerAdapter(LocalFamilyMemberAdapter());
    Hive.registerAdapter(LocalDocumentAdapter());

    // Open all boxes
    await Future.wait([
      Hive.openBox<LocalApplication>(applicationsBoxName),
      Hive.openBox<LocalAddress>(addressesBoxName),
      Hive.openBox<LocalFamilyMember>(familyMembersBoxName),
      Hive.openBox<LocalDocument>(documentsBoxName),
      Hive.openBox(settingsBoxName),
      Hive.openBox(userDataBoxName),
    ]);
  }

  /// Get Applications box
  static Box<LocalApplication> get applicationsBox {
    return Hive.box<LocalApplication>(applicationsBoxName);
  }

  /// Get Addresses box
  static Box<LocalAddress> get addressesBox {
    return Hive.box<LocalAddress>(addressesBoxName);
  }

  /// Get Family Members box
  static Box<LocalFamilyMember> get familyMembersBox {
    return Hive.box<LocalFamilyMember>(familyMembersBoxName);
  }

  /// Get Documents box
  static Box<LocalDocument> get documentsBox {
    return Hive.box<LocalDocument>(documentsBoxName);
  }

  /// Get Settings box
  static Box get settingsBox {
    return Hive.box(settingsBoxName);
  }

  /// Get User Data box
  static Box get userDataBox {
    return Hive.box(userDataBoxName);
  }

  /// Clear all data (for logout or testing)
  static Future<void> clearAll() async {
    await applicationsBox.clear();
    await addressesBox.clear();
    await familyMembersBox.clear();
    await documentsBox.clear();
    await settingsBox.clear();
    await userDataBox.clear();
  }

  /// Close all boxes
  static Future<void> closeAll() async {
    await Hive.close();
  }

  /// Delete application and all related data
  static Future<void> deleteApplication(String applicationLocalId) async {
    // Delete the application
    await applicationsBox.delete(applicationLocalId);

    // Delete related addresses
    final addresses = addressesBox.values
        .where((addr) => addr.applicationLocalId == applicationLocalId)
        .toList();
    for (var address in addresses) {
      await address.delete();
    }

    // Delete related family members
    final familyMembers = familyMembersBox.values
        .where((member) => member.applicationLocalId == applicationLocalId)
        .toList();
    for (var member in familyMembers) {
      await member.delete();
    }

    // Delete related documents
    final documents = documentsBox.values
        .where((doc) => doc.applicationLocalId == applicationLocalId)
        .toList();
    for (var doc in documents) {
      await doc.delete();
    }
  }

  /// Get all applications
  static List<LocalApplication> getAllApplications() {
    return applicationsBox.values.toList();
  }

  /// Get application by local ID
  static LocalApplication? getApplication(String localId) {
    return applicationsBox.get(localId);
  }

  /// Get addresses for an application
  static List<LocalAddress> getAddresses(String applicationLocalId) {
    return addressesBox.values
        .where((addr) => addr.applicationLocalId == applicationLocalId)
        .toList();
  }

  /// Get family members for an application
  static List<LocalFamilyMember> getFamilyMembers(String applicationLocalId) {
    return familyMembersBox.values
        .where((member) => member.applicationLocalId == applicationLocalId)
        .toList();
  }

  /// Get documents for an application
  static List<LocalDocument> getDocuments(String applicationLocalId) {
    return documentsBox.values
        .where((doc) => doc.applicationLocalId == applicationLocalId)
        .toList();
  }

  /// Get current address for an application
  static LocalAddress? getCurrentAddress(String applicationLocalId) {
    return addressesBox.values.firstWhere(
      (addr) => addr.applicationLocalId == applicationLocalId && addr.addressType == 'CURRENT',
      orElse: () => LocalAddress(
        localId: '',
        applicationLocalId: '',
        addressType: 'CURRENT',
      ),
    );
  }

  /// Get permanent address for an application
  static LocalAddress? getPermanentAddress(String applicationLocalId) {
    return addressesBox.values.firstWhere(
      (addr) => addr.applicationLocalId == applicationLocalId && addr.addressType == 'PERMANENT',
      orElse: () => LocalAddress(
        localId: '',
        applicationLocalId: '',
        addressType: 'PERMANENT',
      ),
    );
  }

  /// Get SELF family member (applicant)
  static LocalFamilyMember? getSelfMember(String applicationLocalId) {
    try {
      return familyMembersBox.values.firstWhere(
        (member) => member.applicationLocalId == applicationLocalId && member.relationToApplicant == 'SELF',
      );
    } catch (e) {
      return null;
    }
  }

  /// Database statistics
  static Map<String, int> getStats() {
    return {
      'applications': applicationsBox.length,
      'addresses': addressesBox.length,
      'family_members': familyMembersBox.length,
      'documents': documentsBox.length,
    };
  }
}
